### ISSUE TITLE
Flux Schnell support

### ISSUE THREAD

**Issue by jetjodh** [logtd/ComfyUI-Fluxtapoz#25]
Hi, I couldn't get flux schnell to work reliably with your custom nodes. Is there a specific workflow or param change that you could guide me towards?

**Comment by logtd** [comment]
Hi, I've never tried with Schnell, but there shouldn't be anything stopping it from working. Since Schnell has a lower step count the start_step, end_step, and eta will be extra sensitive. I have gotten it to give good results with the HyperSD Flux lora (8 steps)

Make sure your samplers have the same step counts.
