### ISSUE TITLE
Can this project be used on SDXL?

### ISSUE THREAD

**Issue by chaorenai** [logtd/ComfyUI-Fluxtapoz#29]
Can this project be used on SDXL? If I convert the large model to SDXL, can it run?

**Comment by logtd** [comment]
These nodes were made for Flux, but should also work for SD3 (I've never tested that they'll work out of the box in ComfyUI though). 

They won't work with SDXL since it's not a rectified flow model.  You can search online for "SDXL Unsampling ComfyUI" or something similar, but results may not be as expected.
